### ISSUE TITLE
Docker File Reference

### ISSUE THREAD

**Issue by bishalkc** [logistimo/logistimo-web-service#2]
Docker file references to internal docker repo```FROM docker.logistimo.com:8082/logi-tomcat:latest``` 

Can we use any tomcat image or logi-tomcat is already pre-baked with dependencies?

**Comment by charanm** [comment]
@bishalkc Any tomcat 7 docker will do, there are no pre-baked dependencies inside it. We will update this to use public tomcat 7 docker images.

We prefer pulling tomcat instances from our local servers, and was custom bundled by us initially using the tomcat distribution tar file.

**Comment by bishalkc** [comment]
Thanks @charanm. 
There are some issue with file:/usr/local/tomcat/conf/context.xml, I have attached stack trace for your reference. I will look into and once I get the fix will definitely provide details. 
[logistimo-error.txt](https://github.com/logistimo/logistimo-web-service/files/1036904/logistimo-error.txt)

**Comment by charanm** [comment]
@bishalkc Seems the context.xml is not well-formed. After all there might be some difference in the tomcat docker. Which tomcat 7 docker did you choose?

**Comment by bishalkc** [comment]
tomcat:7.0 ( Starting Servlet Engine: Apache Tomcat/7.0.78)

[context.txt](https://github.com/logistimo/logistimo-web-service/files/1036985/context.txt)

**Comment by charanm** [comment]
Thanks for sharing. the file is truncated after line 34. It is probably to do with the inline replacements performed by the docker run. We will check and update you.
