### ISSUE TITLE
Alter script auto increment value 

### ISSUE THREAD

**Issue by Bhuwanendra** [logistimo/logistimo-web-service#6]
Hi,

Thanks for new version.

I am trying to upgrade from 2.4.0 to the latest version of logistimo application and check alterscript.sql file.
I think you should remove AUTO_INCREMENT=1133465 or AUTO_INCREMENT=1345314  from sql query.

https://github.com/logistimo/logistimo-web-service/blob/master/schema/2.5.0/alterscript.sql

**Comment by mohanrajagr** [comment]
@Bhuwanendra It is the starting key/id for the primary key for the new tables we have created. If we don't specify, the table will start generating ids starting from 1.

**Comment by charanm** [comment]
@Bhuwanendra Were you not able to run this alter script? If so, what was the error. And as suggested by @mohanrajagr, this is not an issue it is preferred to start this sequence at a decent sized number than a single digit.
