### ISSUE TITLE
Cannot build Logistimo v2.8.7, missing com.logistimo:communication-common v1.0.0

### ISSUE THREAD

**Issue by cmosh** [logistimo/logistimo-web-service#8]
Trying to build logistimo 2.8, but the communications common module is missing so the build fails when trying to build the communications model.

`: Could not resolve dependencies for project com.logistimo:logistimo-communications:jar:2.8.0: Failure to find com.logistimo:communication-common:jar:1.0.0 `

**Comment by kgaurav1** [comment]
Hi,

Building this project requires [communication service](https://github.com/logistimo/communications-service) and [collaboration service](https://github.com/logistimo/collaboration-service) as this project has dependencies of these artifacts. One needs to build these artifacts locally. 
Please refer updated build instructions [here](https://github.com/logistimo/logistimo-web-service#build-instructions).

**Comment by cmosh** [comment]
Thanks
